# Generated by Django 5.2.9 on 2026-01-10 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_dietrequest_dietplanassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='dietrequest',
            name='allergies',
            field=models.TextField(blank=True, help_text='List of allergies', null=True),
        ),
        migrations.AddField(
            model_name='dietrequest',
            name='daily_routine',
            field=models.TextField(blank=True, help_text='Brief about daily activity, sleep, etc.', null=True),
        ),
        migrations.AddField(
            model_name='dietrequest',
            name='dietary_history',
            field=models.TextField(blank=True, help_text='Current eating habits', null=True),
        ),
        migrations.AddField(
            model_name='dietrequest',
            name='food_preference',
            field=models.CharField(blank=True, help_text='e.g., Veg, Non-Veg, Vegan', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dietrequest',
            name='medical_conditions',
            field=models.TextField(blank=True, help_text='Any existing medical conditions', null=True),
        ),
    ]
