# Generated by Django 5.2.9 on 2026-01-10 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_chatmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dietplan',
            name='category',
            field=models.CharField(choices=[('Low Carb', 'Low Carb'), ('High Carb', 'High Carb'), ('High Protein', 'High Protein'), ('Balanced', 'Balanced'), ('Keto', 'Keto')], max_length=50),
        ),
    ]
