# Generated by Django 5.2.9 on 2026-01-10 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_dietplan_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='dietrequest',
            name='calculated_needs',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dietplan',
            name='category',
            field=models.CharField(choices=[('Weight Loss', 'Weight Loss'), ('Muscle Gain', 'Muscle Gain'), ('Maintenance', 'Maintenance')], max_length=50),
        ),
    ]
