# Generated by Django 5.2.9 on 2026-01-10 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_dietrequest_calculated_needs_alter_dietplan_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='dietrequest',
            name='activity_level',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
