# Generated by Django 5.2.9 on 2026-01-10 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_dietplan_custom_for_user_dietplan_is_custom'),
    ]

    operations = [
        migrations.AddField(
            model_name='dietplanassignment',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
