# Generated by Django 5.2.10 on 2026-01-10 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_dietplan_calories_dietplan_carbs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutritionistregistration',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
