# Generated by Django 5.2.10 on 2026-01-10 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_nutritionistregistration_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutritionistregistration',
            name='phone',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='phone',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
