# Generated by Django 5.2.10 on 2026-03-28 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_rename_created_at_feedback_submitted_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutritionistregistration',
            name='certificate',
            field=models.FileField(blank=True, null=True, upload_to='certificates/'),
        ),
    ]
