# Generated by Django 5.1.7 on 2025-12-19 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DietPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dietplan', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Low', 'Low Calorie'), ('Medium', 'Medium Calorie'), ('High', 'High Calorie')], max_length=20)),
                ('breakfast', models.TextField()),
                ('lunch', models.TextField()),
                ('dinner', models.TextField()),
                ('intermediate_foods', models.TextField()),
                ('nutritionist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.login')),
            ],
        ),
    ]
