# Generated by Django 5.1.7 on 2025-12-19 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_dietplan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dietplan',
            name='nutritionist',
        ),
        migrations.AddField(
            model_name='dietplan',
            name='loginid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.login'),
        ),
    ]
