# Generated by Django 5.1.7 on 2025-12-22 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_dietplan_nutritionist_dietplan_loginid'),
    ]

    operations = [
        migrations.AddField(
            model_name='dietplan',
            name='activity',
            field=models.TextField(default='pending'),
        ),
        migrations.AddField(
            model_name='dietplan',
            name='drinking_water',
            field=models.TextField(default='pending'),
        ),
        migrations.AddField(
            model_name='dietplan',
            name='sleeping_hours',
            field=models.TextField(default='pending'),
        ),
        migrations.AlterField(
            model_name='dietplan',
            name='category',
            field=models.CharField(choices=[('Low Carb', 'Low Calorie'), ('Medium Carb', 'Medium Calorie'), ('High Carb', 'High Calorie')], max_length=20),
        ),
    ]
