# Generated by Django 5.2.9 on 2026-01-10 04:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_userregistration_activity_level_userregistration_age_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DietRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(blank=True, null=True)),
                ('height', models.FloatField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('health_goal', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(help_text="User's specific request or conditions")),
                ('status', models.CharField(default='pending', max_length=20)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diet_requests', to='app.login')),
            ],
        ),
        migrations.CreateModel(
            name='DietPlanAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='suggested', max_length=20)),
                ('assigned_date', models.DateTimeField(auto_now_add=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('diet_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.dietplan')),
                ('nutritionist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.login')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='app.dietrequest')),
            ],
        ),
    ]
