# Generated by Django 5.2.9 on 2026-01-10 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_dietrequest_activity_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='dietplan',
            name='custom_for_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_plans', to='app.login'),
        ),
        migrations.AddField(
            model_name='dietplan',
            name='is_custom',
            field=models.BooleanField(default=False),
        ),
    ]
