# Generated by Django 5.2.10 on 2026-01-10 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_subscriptionsettings_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='dietplan',
            name='calories',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dietplan',
            name='carbs',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dietplan',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dietplan',
            name='fats',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dietplan',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dietplan',
            name='protein',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
